# Generated by Django 5.2.1 on 2025-06-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_no',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_type',
        ),
    ]
