# Generated by Django 5.2.4 on 2025-07-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_admin_driveruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Parking fee for this booking', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Mark this booking as free parking'),
        ),
    ]
